obj-$(CONFIG_MACH_M7_UL) += board-m7.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-regulator.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-gpiomux.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-storage.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-audio.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-pmic.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-keypad.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-camera.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-gpu.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-rfkill.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-wifi.o
obj-$(CONFIG_MACH_M7_UL) += display/

obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-regulator.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-gpiomux.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-storage.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-audio.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-pmic.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-keypad.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wlj-camera.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wl-gpu.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wl-rfkill.o
obj-$(CONFIG_MACH_M7_WLJ) += board-m7wl-wifi.o
obj-$(CONFIG_MACH_M7_WLJ) += display/

CFLAGS_board-m7-display.o += -Idrivers/video
CFLAGS_board-m7-audio.o += -Isound/soc/msm
